version: "3"

services:
  # nats-server:
  #   image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/store-microservices-418622/image-registry/client-gateway-production
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    # command: yarn start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-microservice:
    image: southamerica-west1-docker.pkg.dev/store-microservices-418622/image-registry/auth-microservice-production
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile.prod
      args:
        - AUTH_SERVICE_DATABASE_URL=${AUTH_SERVICE_DATABASE_URL}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - DATABASE_URL=${AUTH_SERVICE_DATABASE_URL}
      - JWT_SECRET=${AUTH_SERVICE_JWT_SECRET}
      - NATS_SERVERS=${NATS_SERVERS}

  products-microservice:
    image: southamerica-west1-docker.pkg.dev/store-microservices-418622/image-registry/products-microservice-production
    build:
      context: ./products-microservice
      dockerfile: Dockerfile.prod
    ports:
      - "${PRODUCTS_SERVICE_PORT}:${PRODUCTS_SERVICE_PORT}"
    environment:
      - PORT=${PRODUCTS_SERVICE_PORT}
      - DATABASE_URL=${PRODUCTS_SERVICE_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  # Orders MS
  orders-microservice:
    image: southamerica-west1-docker.pkg.dev/store-microservices-418622/image-registry/orders-microservice-production
    build:
      context: ./orders-microservice
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_SERVICE_DATABASE_URL=${ORDERS_SERVICE_DATABASE_URL}
    ports:
      - "${ORDERS_SERVICE_PORT}:${ORDERS_SERVICE_PORT}"
    environment:
      - PORT=${ORDERS_SERVICE_PORT}
      - DATABASE_URL=${ORDERS_SERVICE_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  # Payments MS
  payments-microservice:
    image: southamerica-west1-docker.pkg.dev/store-microservices-418622/image-registry/payments-microservice-production
    build:
      context: ./payments-microservice
      dockerfile: Dockerfile.prod
    ports:
      - "${PAYMENTS_SERVICE_PORT}:3003"
    environment:
      - PORT=${PAYMENTS_SERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
